format = """
$username\
$directory\
$hostname\
${custom.toolbox}\
$git_branch\
${custom.dirty}\
$line_break\
$aws\
$terraform\
$character"""

# newline is in my format string
add_newline = false

[username]
style_user = "bold green"
show_always = true

[hostname]
ssh_only = true
format =  "in [$hostname](bold red) "

[custom.toolbox]
when = "hostname | grep 'toolbx'"
command = "cat /run/.containerenv | grep 'name' | cut -d \\= -f2 | sed 's/\"//g'"
format = "in [󱁤 $output](yellow) "

[directory]
truncate_to_repo = false
style = "bold blue"

# ignores untracked files for performance
[custom.dirty]
when = "(git rev-parse --is-inside-work-tree >/dev/null 2>&1) && (! git diff --no-ext-diff --quiet --exit-code)"
format = "[*](red)"

# [aws]
# format = ' [$symbol ($profile )(\($region\))]($style)'
# style = 'bold blue'
# symbol = 'aws'
#
# [terraform]
# format = ' [tf $workspace]($style)'

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold yellow)"
format = " $symbol "
