format = """
$username\
$directory\
$hostname\
${custom.toolbox}\
$git_branch\
${custom.dirty}
$character"""

# newline is in my format string
add_newline = false

[username]
style_user = "bold green"
show_always = true

[hostname]
ssh_only = true
format =  "in [$hostname](bold red) "

[custom.toolbox]
when = "hostname | grep 'toolbox'"
command = "cat /run/.containerenv | grep 'name' | cut -d \\= -f2 | sed 's/\"//g'"
format = "in [󱁤 $output](yellow) "

[directory]
truncate_to_repo = false
style = "bold blue"

# ignores untracked files for performance
[custom.dirty]
when = "(git rev-parse --is-inside-work-tree >/dev/null 2>&1) && (! git diff --no-ext-diff --quiet --exit-code)"
format = "[*](red)"

# [cmd_duration]
# min_time = 5000
# format = "[took $duration](bold yellow)\n"

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold yellow)"
format = " $symbol "
