# Colors (One Dark)
[colors.normal]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828997"
yellow = "#e5c07b"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.selection]
background = "#3e4451"
text = "CellForeground"

[font]
size = 11
normal = { family = "Hack Nerd Font", style = "Regular" }
offset = { x = 0, y = 1 }

[window]
dynamic_padding = true
dimensions = { columns = 80, lines = 30 }
padding = { x = 2, y = 2 }
opacity = 0.96

[keyboard]
bindings = [
  { key = "V", action = "Paste",  mods = "Control" },
  { key = "F11", action = "ToggleFullscreen" },
]

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"
