#!/bin/zsh

clipboard() {
  if type xclip &>/dev/null; then
    cat "$@" | xclip -selection clipboard
  else
    print_osc52 "$@"
  fi
}

# copy via OSC 52
# https://sunaku.github.io/tmux-yank-osc52.html
# newer tmux does not need the tmux escape anymore
# https://github.com/ojroques/vim-oscyank/issues/26
print_osc52() {
  printf "\033]52;c;$( cat "$@" | base64 | tr -d '\r\n' )\a"
}
