#!/usr/bin/env zsh
# mnemonic: [F]uzzy [B]ranch [D]elete

# use [tab] to select one or branches to delete

function fuzzy_branch_delete() {
  git branch | fzf --multi --header='[branch:delete]' | xargs git branch -D
}

alias fbd='fuzzy_branch_delete'
