#!/usr/bin/env zsh
# mnemonic: [F]uzzy [K]ill [P]rocess

# show output of "ps aux", use [tab] to select one or multiple entries
# press [enter] to kill selected processes or press [escape] to exit completely.

function fuzzy_kill_process() {
  ps aux | fzf --multi --header='[kill:process]' | awk {'print$2'} | xargs kill -9
}

alias fkp='fuzzy_kill_process'
