#!/bin/zsh

# colors (onedark)
green="#98c379"
blue="#61afef"
yellow="#e5c07b"
magenta="#c678dd"

# fzf configuration
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git/*"'
export FZF_DEFAULT_OPTS="--reverse --height=50%
--color=dark
--color=fg:-1,bg:-1,hl:$magenta
--color=fg+:#ffffff,bg+:#4b5263,hl+:#d858fe
--color=info:$green,prompt:$blue,pointer:$magenta
--color=marker:$yellow,spinner:$blue,header:$blue,gutter:-1"

# source fzf
# git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
# then run ~/.fzf/install to create this file.
if [ -f ~/.fzf.zsh ]; then
  source ~/.fzf.zsh
fi

# source fzf-tab
# git clone --depth 1 https://github.com/Aloxaf/fzf-tab ~/.fzf-tab
if [ -d ~/.fzf-tab ]; then
  zstyle ':fzf-tab:*' use-fzf-default-opts yes
  source ~/.fzf-tab/fzf-tab.plugin.zsh
fi
