#!/usr/bin/env zsh

# fuzzy search the git log with a preview

# thanks to this article! https://bluz71.github.io/2018/11/26/fuzzy-finding-in-bash-with-fzf.html

fzf_git_log() {
  local selections=$(
    git log --color=always --format="%C(yellow)%h%C(red)%d%C(reset) - %C(bold green)(%ar)%C(reset) %s %C(blue)<%an>%C(reset)" "$@" |
      fzf --ansi --no-sort --no-height --reverse --multi \
          --preview "echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
                      xargs -I@ sh -c 'git show --color=always @'"
    )

  if [[ -n $selections ]]; then
    echo "$selections" | sed 's/^[* |]*//' | cut -d' ' -f1
  fi
}

alias gl='fzf_git_log'
