#!/bin/zsh

# push the current branch, confirm master/main push.
# allow force push unless master/main
git_push() {
  if git rev-parse --git-dir > /dev/null 2>&1; then
    branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
    args="$@"

    # filter -d command since I never want this and typo it often
    if [[ "$args" =~ "-d" ]]; then
      echo "-d not allowed"
      return 1
    fi

    if [[ "$branch" != "HEAD" ]]; then
      if [[ "$branch" = "master" || "$branch" = "main" ]]; then

        echo "push $branch, Are you sure? (y/n)"
        read REPLY
        if [[ $REPLY =~ ^[Yy]$ ]]; then
          if [[ -n $args ]]; then
            echo "no force push $branch"
            return 1
          else
            git push origin $branch
          fi
        else
          echo 'git push aborted.'
          return 1
        fi

      # branch is not master or main, allow options like force
      else
        git push origin $branch $@
      fi
    else
      echo 'not on a branch'
      return 1
    fi
  else
    echo 'not a git repo'
    return 1
  fi
}

alias gp='git_push'
