#!/usr/bin/env zsh
# mnemonic: [G]it [R]ebase

# rebase the current branch against fresh master
function git_rebase {
  local curbranch=`git rev-parse --abbrev-ref HEAD`
  git checkout master
  git pull origin master
  git checkout $curbranch
  git rebase master
}

alias gr='git_rebase'
