#!/usr/bin/env zsh
# mnemonic: [K]ill [P]rocess

# show output of "ps -ef", use [tab] to select one or multiple entries
# press [enter] to kill selected processes or press [escape] to exit completely.

function fuzzy_kill_process() {
  local pid=$(ps -ef | sed 1d | eval "fzf ${FZF_DEFAULT_OPTS} -m --header='[kill:process]'" | awk '{print $2}')

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi
}

alias kp='fuzzy_kill_process'
