#!/bin/zsh

function man() {
  local -x LESS_TERMCAP_mb=$'\e[1;32m'
  local -x LESS_TERMCAP_md=$'\e[1;32m'
  local -x LESS_TERMCAP_me=$'\e[0m'
  local -x LESS_TERMCAP_se=$'\e[0m'
  local -x LESS_TERMCAP_so=$'\e[01;33m'
  local -x LESS_TERMCAP_ue=$'\e[0m'
  local -x LESS_TERMCAP_us=$'\e[1;4;31m'

  command man "$@"
}
