#!/bin/zsh

podman_debug() {
  local shell="bash"
  if [[ $# -eq 2 ]]; then
    local shell="${2}"
  fi
  podman exec -it "$1" "$shell"
}

podman_cleanup() {
  podman images --format "{{.ID}} {{.Repository}}:{{.Tag}}" | fzf --multi | awk '{print $1}' | xargs -r podman rmi --force
}
