#!/bin/zsh

# rspec or rails tests
# based on Gemfile contents
rails_test() {
  if grep -q "rspec" Gemfile; then
    bundle exec rspec $@
  elif grep -q "rails', '5" Gemfile; then
    rails test $@
  else
    echo "couldn't infer test command";
  fi
}

alias rt='rails_test'
