#!/bin/zsh

# if tmux is available but no session exists, create one and attach to it.
tmuxify() {
  if hash tmux &> /dev/null; then
    if tmux ls &> /dev/null; then
      # tmux is already running
    else
      # create a default tmux session with my notes open
      tmux new-session -s main -n main -d
      tmux new-window -t main:2 -n notes -c $HOME/notes nvim +NvimTreeOpen
      tmux select-window -t main:1
      tmux attach
    fi
  fi
}
