#!/bin/zsh

# if tmux is available but no session exists, create one and attach to it.
tmuxify() {
  if hash tmux &> /dev/null; then
    if tmux ls &> /dev/null; then
      # tmux is already running
    else
      # create a default tmux session
      local session="main"
      tmux new-session -s $session -n dots -d -c $HOME/dotfiles nvim +NvimTreeOpen
      tmux new-window -t $session:2 -n notes -c $HOME/notes nvim +NvimTreeOpen
      tmux select-window -t $session:1
      tmux attach -t $session
    fi
  fi
}
