#!/bin/bash

export EDITOR="vim"

# add line number to LESS prompt
export LESS='-RS#3NM~g'

# history
export HISTSIZE=10000
export HISTFILESIZE=10000
shopt -s histappend
export PROMPT_COMMAND='history -a'
export HISTCONTROL="ignoredups"
export HISTCONTROL=erasedups

# help with case in completion
bind 'set completion-ignore-case on'
